In [23]:
sales_pipeline.groupby("deal_stage")["close_value"].agg(
    ["count","sum","mean","median"]
)

             count         sum         mean  median
deal_stage
Engaging         0         0.0          NaN     NaN
Lost          2473         0.0     0.000000     0.0
Prospecting      0         0.0          NaN     NaN
Won           4238  10005534.0  2360.909391  1117.0

In [16]:
sales_pipeline.groupby("product")["opportunity_id"].count().sort_values(ascending=False)

product
GTX Basic         1866
MG Special        1651
GTXPro            1480
MG Advanced       1412
GTX Plus Basic    1383
GTX Plus Pro       968
GTK 500             40
Name: opportunity_id, dtype: int64

In [15]:
sales_pipeline.groupby("account")["opportunity_id"].count().describe()

count     85.000000
mean      86.764706
std       29.326831
min       51.000000
25%       66.000000
50%       83.000000
75%       98.000000
max      200.000000
Name: opportunity_id, dtype: float64

In [14]:
sales_teams["sales_agent"].nunique()

35

In [ ]:
products["product"].nunique()

85

In [12]:
accounts["account"].nunique()

85

In [7]:
sales_pipeline.nunique()

opportunity_id    8800
sales_agent         30
product              7
account             85
deal_stage           4
engage_date        421
close_date         306
close_value       2051
dtype: int64

In [17]:
sales_pipeline[["engage_date","close_date"]].head()

  engage_date  close_date
0  2016-10-20  2017-03-01
1  2016-10-25  2017-03-11
2  2016-10-25  2017-03-07
3  2016-10-25  2017-03-09
4  2016-10-25  2017-03-02

In [18]:
sales_pipeline[["engage_date","close_date"]].info()

<class 'pandas.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   engage_date  8300 non-null   str
 1   close_date   6711 non-null   str
dtypes: str(2)
memory usage: 286.4 KB

In [19]:
sales_pipeline["deal_stage"].value_counts()

deal_stage
Won            4238
Lost           2473
Engaging       1589
Prospecting     500
Name: count, dtype: int64

In [20]:
sales_pipeline["deal_stage"].value_counts(normalize=True) * 100

deal_stage
Won            48.159091
Lost           28.102273
Engaging       18.056818
Prospecting     5.681818
Name: proportion, dtype: float64

In [21]:

sales_pipeline.head()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0

In [22]:
sales_pipeline.columns

Index(['opportunity_id', 'sales_agent', 'product', 'account', 'deal_stage',
       'engage_date', 'close_date', 'close_value'],
      dtype='str')

In [3]:
for name, df in {
    "accounts": accounts,
    "products": products,
    "sales_pipeline": sales_pipeline,
    "sales_teams": sales_teams
}.items():

    print(f"\n{'='*50}")
    print(name.upper())
    print(f"{'='*50}")

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicates")
    print(df.duplicated().sum())

==================================================
ACCOUNTS
==================================================

Missing Values
account              0
sector               0
year_established     0
revenue              0
employees            0
office_location      0
subsidiary_of       70
dtype: int64

Duplicates
0

==================================================
PRODUCTS
==================================================

Missing Values
product        0
series         0
sales_price    0
dtype: int64

Duplicates
0

==================================================
SALES_PIPELINE
==================================================

Missing Values
opportunity_id       0
sales_agent          0
product              0
account           1425
deal_stage           0
engage_date        500
close_date        2089
close_value       2089
dtype: int64

Duplicates
0

==================================================
SALES_TEAMS
==================================================

Missing Values
sales_agent        0
manager            0
regional_office    0
dtype: int64

Duplicates
0

In [2]:
accounts.info()
accounts.head()

products.info()
products.head()

sales_pipeline.info()
sales_pipeline.head()

sales_teams.info()
sales_teams.head()

<class 'pandas.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account           85 non-null     str
 1   sector            85 non-null     str
 2   year_established  85 non-null     int64
 3   revenue           85 non-null     float64
 4   employees         85 non-null     int64
 5   office_location   85 non-null     str
 6   subsidiary_of     15 non-null     str
dtypes: float64(1), int64(2), str(4)
memory usage: 7.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product      7 non-null      str
 1   series       7 non-null      str
 2   sales_price  7 non-null      int64
dtypes: int64(1), str(2)
memory usage: 389.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  8800 non-null   str
 1   sales_agent     8800 non-null   str
 2   product         8800 non-null   str
 3   account         7375 non-null   str
 4   deal_stage      8800 non-null   str
 5   engage_date     8300 non-null   str
 6   close_date      6711 non-null   str
 7   close_value     6711 non-null   float64
dtypes: float64(1), str(7)
memory usage: 1.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sales_agent      35 non-null     str
 1   manager          35 non-null     str
 2   regional_office  35 non-null     str
dtypes: str(3)
memory usage: 2.0 KB

         sales_agent           manager regional_office
0      Anna Snelling  Dustin Brinkmann         Central
1     Cecily Lampkin  Dustin Brinkmann         Central
2  Versie Hillebrand  Dustin Brinkmann         Central
3    Lajuana Vencill  Dustin Brinkmann         Central
4        Moses Frase  Dustin Brinkmann         Central

In [1]:
import pandas as pd

accounts = pd.read_csv("../data/raw/accounts.csv")
products = pd.read_csv("../data/raw/products.csv")
sales_pipeline = pd.read_csv("../data/raw/sales_pipeline.csv")
sales_teams = pd.read_csv("../data/raw/sales_teams.csv")

print("Accounts:", accounts.shape)
print("Products:", products.shape)
print("Sales Pipeline:", sales_pipeline.shape)
print("Sales Teams:", sales_teams.shape)

Accounts: (85, 7)
Products: (7, 3)
Sales Pipeline: (8800, 8)
Sales Teams: (35, 3)